#Teacher model

teacher: 
  type: DeformableDETR
  backbone: 
    type: Joiner
    pos_hidden_dim: 256
  transformer:
    type: DeformableTransformer
    d_model: 256
    nhead: 8
    num_encoder_layers: 6
    num_decoder_layers: 6
    dim_feedforward: 2048
    dropout: 0.0
    activation: "relu"
    return_intermediate_dec: True
    num_feature_levels: 5
    two_stage: True
    two_stage_num_proposals: 900
    assign_first_stage: True
  num_classes: 91
  num_queries: 900
  num_feature_levels: 5 
  with_box_refine: True
  two_stage: True
